### ISSUE TITLE
Using vergesort Backed by ska::sort

### ISSUE THREAD

**Issue by victorstewart** [Morwenn/vergesort#12]
I was looking to use vergesort backed by ska::sort to sort some already sorted (but occasionally random) std::vectors after inserting a few more elements... saw this mentioned and the benchmarks posted...

but when I was checking out your code, there doesn't seem to be any place to template in the backing sort? It seems to just be hardcoded in?

even if that is the case, can you post the code with vergesort backed by ska::sort? :)

**Comment by Morwenn** [comment]
I actually integrated an improvement like this one in another library of mine, cpp-sort. It notably contains the template [`verge_adapter`][1] which actually runs vergesort on top of a chosen sorter (a sorter is a function object implementing a sorting algorithm).

I haven't tried to run `verge_adapter` on top of `ska_sorter` because vergesort is a comparison sort and ska_sort doesn't accept a custom comparison function since it is a hybrid radix sort and is therefore not based on comparison. That said, most sorters in cpp-sort - including `ska_sorter` - accept `std::less<>` as an argument (as some kind of tag meaning that once the algorithm has run, you can use `std::is_sorted` with `std::less<>` and it should return `true`), so the following code might do what you want (untested):

```cpp
#include <cpp-sort/adapters/verge_adapter.h>
#include <cpp-sort/sorters/ska_sorter.h>

int main()
{
    auto some_collection = /* whatever */;
    cppsort::verge_adapter<cppsort::ska_sorter> sort;
    sort(collection); // Implicitly uses std::less<> so it should work
}
```

This is roughly what I used to test vergesort on top of other comparison sorts (it might have been more manual when I generated the benchmarks in this project), if you're lucky it will also work with ska_sort :) And if you're not you might get a few hundred lines of template errors.


  [1]: https://github.com/Morwenn/cpp-sort/wiki/Sorter-adapters#verge_adapter

**Comment by victorstewart** [comment]
not all heros wear capes!

So with a custom object say...

```
class Person {
public:

   std::basic_string<char> token;
   uint16_t followerCount;
};
```

all i do is...

```
std::vector<Person*> people;
// fill container
cppsort::verge_adapter<cppsort::ska_sorter> sort;
sort(people, [] (const Person* person) -> uint16_t { return person->followerCount; }):
```

tested and works. thanks!

**Comment by Morwenn** [comment]
Glad it worked ;)

**Comment by Morwenn** [comment]
Can this issue be closed or are there further expectations?

**Comment by victorstewart** [comment]
all good!
